### ISSUE TITLE
Compilation failing on void linux

### ISSUE THREAD

**Issue by heppu** [pop-os/keyboard-configurator#220]
Just got my launch lite and I'm trying to install keyboard-configurator on void linux.
I have installed devel deps by running:  `sudo xbps-install -S gtk+3-devel hidapi-devel eudev-libudev-devel` and after that cloned the repo. This is what I get when trying to install configurator:

```
$ CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true RUST_BACKTRACE=full cargo run --release
   Compiling system76-keyboard-configurator v1.3.10 (/home/heppu/keyboard-configurator)
error: failed to run custom build command for `system76-keyboard-configurator v1.3.10 (/home/heppu/keyboard-configurator)`

Caused by:
  process didn't exit successfully: `/home/heppu/keyboard-configurator/target/release/build/system76-keyboard-configurator-62edf274c072dd18/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/heppu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glib-build-tools-0.17.10/src/lib.rs:33:10
  stack backtrace:
     0:     0x5572e3176391 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1a102dbfc16b6908
     1:     0x5572e319956e - core::fmt::write::he54e1af1cdf1c5fa
     2:     0x5572e3173aa7 - std::io::Write::write_fmt::hc1455858455944b2
     3:     0x5572e31761a5 - std::sys_common::backtrace::print::h246830192471726c
     4:     0x5572e3177674 - std::panicking::default_hook::{{closure}}::h43349c26e5286f65
     5:     0x5572e317739a - std::panicking::default_hook::h99b7de76c6f52661
     6:     0x5572e3177c25 - std::panicking::rust_panic_with_hook::hddbf738220556b3f
     7:     0x5572e3177b27 - std::panicking::begin_panic_handler::{{closure}}::had57ff47e1a78b9a
     8:     0x5572e31767f6 - std::sys_common::backtrace::__rust_end_short_backtrace::h35b33a0d0a280d00
     9:     0x5572e3177832 - rust_begin_unwind
    10:     0x5572e314f1b3 - core::panicking::panic_fmt::h845bf998f7bfd3e8
    11:     0x5572e314f593 - core::result::unwrap_failed::h5040bf9f6218f241
    12:     0x5572e31549a0 - core::result::Result<T,E>::unwrap::hf1e3df4c8a22ee91
                                 at /builddir/rust-1.72.1/library/core/src/result.rs:1076:23
    13:     0x5572e315390c - glib_build_tools::compile_resources::hb9b1de5072011653
                                 at /home/heppu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glib-build-tools-0.17.10/src/lib.rs:28:18
    14:     0x5572e31535ab - build_script_build::main::h9240317e1bb53e11
                                 at /home/heppu/keyboard-configurator/build.rs:2:5
    15:     0x5572e31508ab - core::ops::function::FnOnce::call_once::h7da47e0b457d1dbc
                                 at /builddir/rust-1.72.1/library/core/src/ops/function.rs:250:5
    16:     0x5572e314fd4e - std::sys_common::backtrace::__rust_begin_short_backtrace::hda5b918e4e2ed965
                                 at /builddir/rust-1.72.1/library/std/src/sys_common/backtrace.rs:135:18
    17:     0x5572e31504d1 - std::rt::lang_start::{{closure}}::h79917b2856701209
                                 at /builddir/rust-1.72.1/library/std/src/rt.rs:166:18
    18:     0x5572e31708f8 - std::rt::lang_start_internal::h3150d0c70dbaa64b
    19:     0x5572e31504aa - std::rt::lang_start::ha9b3902973eb4e37
                                 at /builddir/rust-1.72.1/library/std/src/rt.rs:165:17
    20:     0x5572e31535ce - main
    21:     0x7f46f90a118c - __libc_start_call_main
                                 at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    22:     0x7f46f90a1245 - __libc_start_main_impl
                                 at ./csu/../csu/libc-start.c:381:3
    23:     0x5572e314f851 - _start
                                 at /builddir/glibc-2.36/csu/../sysdeps/x86_64/start.S:115
    24:                0x0 - <unknown>
    ```

**Comment by heppu** [comment]
I also tested with v1.3.9 and got the same error.

**Comment by heppu** [comment]
Looks like installing `glib-devel` was required on void so if anyone else is running into same issues these are the packages that are required for void linux:
```sh
xbps-install -S gtk+3-devel hidapi-devel eudev-libudev-devel glib-devel
```
